import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, BriefcaseBusiness, Building2, Check, GraduationCap, Globe2, HeartPulse, Leaf, Menu, Search, ShieldCheck, Stethoscope, Target, Users, PlayCircle, Sparkles } from "lucide-react";

const audiences = [
  { icon: Users, title: "Individuals & Families", text: "Supporting healthier lives at every stage.", image: "/expertise-maternal.jpg", tone: "green" },
  { icon: Stethoscope, title: "Healthcare Organizations", text: "Collaborating for better outcomes.", image: "/expertise-literacy.jpg", tone: "purple" },
  { icon: GraduationCap, title: "Schools", text: "Building healthier learning environments.", image: "/expertise-school.jpg", tone: "teal" },
  { icon: BriefcaseBusiness, title: "Employers", text: "Healthier workplaces. More productive tomorrows.", image: "/expertise-population.jpg", tone: "green" },
  { icon: Building2, title: "Government & Communities", text: "Stronger communities through partnership.", image: "/hero-family.jpg", tone: "purple" },
];
const programs = [["National Diabetes Prevention Program (DPP)","Prevent. Educate. Empower."],["Diabetes Education & Support","Practical tools for healthier living."],["Lifestyle Change Coaching","Real support. Lasting results."]];
const solutions=["Consulting & Technical Assistance","Program Development & Implementation","Workforce Training & Education","Community Engagement","Evaluation & Quality Improvement"];
const values=[{icon:ShieldCheck,label:"Evidence-Based"},{icon:Users,label:"Nurse-Led"},{icon:Target,label:"Population-Health Focused"},{icon:Users,label:"Community-Centered"},{icon:Globe2,label:"Culturally Responsive"},{icon:Leaf,label:"Prevention-Focused"}];
function Flourish(){return <div className="flourish" aria-hidden="true"><span/><Leaf/><span/></div>}
export default function Home(){return <main>
<header className="siteHeader"><div className="nav wrap"><a className="brand" href="#top"><Image src="/nova-logo.png" alt="NOVA Wellness & Lifestyle Institute" width={280} height={130} priority/></a><nav aria-label="Primary navigation"><a className="active" href="#top">Home</a><a href="#services">Services</a><a href="#organizations">For Organizations</a><a href="#education">Education & Training</a><Link href="/learn">NOVA Learning</Link><a href="#resources">Resources</a><a href="#about">About</a><a href="#contact">Contact</a><Search size={16}/></nav><div className="navActions"><Link className="loginPill" href="/login">Log In</Link><Link className="button compact" href="/signup">Sign Up</Link></div><button className="menu" aria-label="Open navigation"><Menu/></button></div></header>
<section className="hero v3Hero" id="top"><div className="heroPhoto" aria-hidden="true"/><div className="heroGlow"/><div className="wrap heroInner"><div className="heroCopy"><span className="eyebrow">Healthier people. Stronger communities.</span><h1><span>NOVA</span>Wellness &amp; Lifestyle Institute</h1><h2>Advancing health through prevention, education &amp; partnership.</h2><p>We extend evidence-based care beyond the clinic by partnering with individuals, families, healthcare providers, schools, employers, and community organizations to improve health literacy, strengthen prevention, address health needs, and support sustainable healthy lifestyles.</p><div className="actions"><a className="button" href="#services">Explore Our Services <ArrowRight size={17}/></a><a className="button secondary" href="#about">Learn About NOVA</a></div><div className="heroPrinciples"><span><Leaf/>Prevent.</span><span><BookOpen/>Educate.</span><span><Users/>Empower.</span><span><Target/>Thrive.</span></div></div></div></section>

<section className="learningShowcase" id="education"><div className="wrap learningGrid"><div className="learningCopy"><span className="eyebrow">NOVA Learning</span><h2>Health Education<br/>That Moves With You</h2><h3>Practical. Flexible. Evidence-based.</h3><p>Access expert-led courses, tools and resources to build healthier habits, gain knowledge, and make a lasting impact — anytime, anywhere.</p><div className="actions"><Link className="button" href="/learn">Explore Courses <ArrowRight size={17}/></Link><Link className="button secondary" href="/signup">Sign Up</Link><Link className="textButton" href="/login">Log In</Link></div><div className="learningBenefits"><span><PlayCircle/>On-demand learning</span><span><Users/>Expert-led</span><span><ShieldCheck/>Practical tools</span><span><Target/>Track your progress</span></div></div><div className="deviceScene" aria-label="NOVA Learning platform preview"><div className="orb orb1"/><div className="orb orb2"/><div className="bookStack"><i>HEALTHY PEOPLE</i><i>STRONGER COMMUNITIES</i><i>BRIGHTER FUTURES</i></div><div className="laptop"><div className="screen"><div className="screenTop"><span className="miniLogo">♡ NOVA</span><span>Welcome back, Learner</span></div><div className="screenBody"><aside>Home<br/>My Courses<br/>Calendar<br/>Resources</aside><div><strong>NOVA Learning</strong><small>Learn. Apply. Make an Impact.</small><div className="screenCards"><b>Diabetes Prevention</b><b>Maternal &amp; Family Health</b><b>Health Literacy</b><b>School &amp; Community Health</b></div></div></div></div><div className="keyboard"/></div><div className="floatBadge"><Sparkles/><b>Learn • Grow • Thrive</b></div></div></div></section>

<section className="serve section"><div className="wrap"><div className="sectionHead splitHead"><div><h2>Who We Serve</h2><Flourish/></div><p>Different needs. A healthier tomorrow — together.</p></div><div className="audienceGrid photoAudience">{audiences.map(({icon:Icon,title,text,image,tone})=><article key={title}><div className="audiencePhoto" style={{backgroundImage:`url(${image})`}}/><div className="audienceBody"><div className={`roundIcon ${tone}`}><Icon/></div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

<section className="details section" id="services"><div className="wrap detailGrid"><article><h2>Featured Programs</h2><Flourish/><div className="programs">{programs.map(([title,text],i)=><a href="#contact" key={title}><span className={`miniIcon m${i+1}`}>{i===0?<Leaf/>:<Stethoscope/>}</span><span><strong>{title}</strong><small>{text}</small></span><ArrowRight/></a>)}</div></article><article id="organizations"><h2>Solutions for Organizations</h2><Flourish/><ul>{solutions.map(x=><li key={x}><Check/> {x}</li>)}</ul><a className="button" href="#contact">Partner With NOVA <ArrowRight size={17}/></a></article><article><h2>International Public<br/>Health Consulting</h2><Flourish/><div className="international"><Globe2/><p><b>Global expertise. Local impact.</b><br/>We partner with organizations worldwide to strengthen health systems, build capacity, and advance healthier communities.</p></div><a className="button secondary" href="#contact">Explore Opportunities <ArrowRight size={17}/></a></article></div></section>

<section className="why" id="about"><div className="wrap"><h2>Why NOVA?</h2><Flourish/><div className="whyGrid">{values.map(({icon:Icon,label})=><div key={label}><Icon/><strong>{label}</strong></div>)}<blockquote>“Healthier People.<br/>Stronger Communities.<br/>A Brighter Future.”</blockquote></div></div></section>
<section className="cta" id="contact"><div className="wrap"><h2>Ready to Make an Impact Together?</h2><p>Let’s discuss how NOVA can support your health and wellness goals.</p><a className="button" href="mailto:charity.nwanevu@gmail.com">Request a Consultation <ArrowRight size={17}/></a></div></section>
<footer id="resources"><div className="wrap footerTop"><div className="footerBrand"><Image src="/nova-logo.png" alt="NOVA Wellness & Lifestyle Institute" width={230} height={110}/></div><div><h3>Quick Links</h3><div className="linkCols"><p><a href="#top">Home</a><a href="#services">Services</a><a href="#organizations">For Organizations</a></p><p><a href="#education">Education & Training</a><Link href="/learn">NOVA Learning</Link><a href="#about">About</a></p><p><a href="#resources">Resources</a><a href="#contact">Contact</a></p></div></div><div><h3>Stay Informed</h3><p>Subscribe to NOVA updates</p><div className="subscribe"><span>Your email address</span><ArrowRight/></div></div></div><div className="footerBottom wrap"><span>© 2026 NOVA Wellness &amp; Lifestyle Institute. All rights reserved.</span><span>Formerly NOVA Diabetes Prevention &amp; Management, Inc.</span><span>Privacy Policy &nbsp; | &nbsp; Terms of Use &nbsp; | &nbsp; Accessibility</span></div></footer>
</main>}
